export const API_PATHS = {
  auth: {
    whoami: "/auth/whoami",
    login: "/auth/login",
    register: "/auth/user",
    user: (id: string) => `/auth/user/${id}`,
    google: "/auth/google",
    googleCallback: "/auth/google/callback",
    logout: "/auth/logout",
  },
  rooms: {
    list: (userId: string) => `/users/${userId}/rooms`,
    get: (id: string) => `/rooms/${id}`,
    create: "/rooms",
    update: (id: string) => `/rooms/${id}`,
    delete: (id: string) => `/rooms/${id}`,
    members: (roomId: string) => `/rooms/${roomId}/members`,
    member: (roomId: string, userId: string) => `/rooms/${roomId}/members/${userId}`,
    invite: (roomId: string) => `/rooms/${roomId}/invite`,
    joinInvite: (token: string) => `/rooms/invite/${token}/join`,
    pop: (roomId: string) => `/rooms/${roomId}/pop`,
  },
  chat: {
    messages: (roomId: string) => `/chat/rooms/${roomId}/messages`,
    message: (roomId: string, messageId: string) => `/chat/rooms/${roomId}/messages/${messageId}`,
  },
  admin: {
    users: "/auth/admin/users",
    user: (id: string) => `/auth/admin/users/${id}`,
    userRole: (id: string) => `/auth/admin/users/${id}/role`,
    userRestore: (id: string) => `/auth/admin/users/${id}/restore`,
    userSessions: (id: string) => `/auth/admin/users/${id}/sessions`,
    sessions: "/auth/admin/sessions",
    session: (id: string) => `/auth/admin/sessions/${id}`,
    audit: "/auth/admin/audit",
    statsUsers: "/auth/admin/stats/users",
    statsSessions: "/auth/admin/stats/sessions",
    rooms: "/admin/rooms",
    room: (id: string) => `/admin/rooms/${id}`,
    roomMembers: (roomId: string) => `/admin/rooms/${roomId}/members`,
    roomMember: (roomId: string, userId: string) => `/admin/rooms/${roomId}/members/${userId}`,
    userRooms: (userId: string) => `/admin/users/${userId}/rooms`,
    statsRooms: "/admin/stats/rooms",
    messages: "/chat/admin/messages",
    message: (id: string) => `/chat/admin/messages/${id}`,
    statsMessages: "/chat/admin/stats/messages",
  },
} as const
